def basic():
    print("☼")
    print("    ")
    print(" ☻  ")
    print("/▌\\")
    print("/ \\   ⚘⚘  ⚘")
def basic_mushu():
    print("☼")
    print("    ")
    print(" ☻           (\\   /)") 
    print("/▌\\          (￣个￣)")
    print("/ \\   ⚘⚘  ⚘  (      )")
def coffee_heal():
    print(" ☻ ☕ ")
    print("/▌/ ")
    print("/ \\ ")
def danger():
    print("        / \\") 
    print(" ☻     / ! \\")
    print("/▌\\   /_____\\")
    print("/ \\             ◎◎◎")
    print("Oh no! A mob is near!")
def bunny_mob():
    print("   ↑    ")
    print(" ☻ |        (\_/)")
    print("/▌\\|        ('.')")
    print("/ \\         (> <)")
def attack_bunny_mob():
    print(" ☻__---> (\_/)")
    print("/▌       ('.')")
    print("/ \\      (> <)")
def bunny_attack():
    print(" ☻    (\_/)")
    print("/▌\\   ('.')")
    print("/ \\<<<(  <)")
def dead_bunny_mob():
    print(" V I C T O R Y!")
    print("   ↑")
    print(" ☻ |   (\_/)")
    print("/▌\\|   (+.+)")
    print("/ \\    (^ ^)")
def dead_man():
    print(" D E F E A T . . .")
    print("     (\_/)")
    print("     ('.')")
    print("⚫▂__(> <)")
def travelling_cart():
    print("_______________")
    print("|             |")
    print("|             |")
    print("|  (\\   /)    |")
    print("|__(￣个￣)____|")
    print("|             |")
    print("|   S H O P   |")
    print("|_____________|")
    print()
    print(" ☻          ⚘")
    print("/▌\\        ⚘ ⚘") 
    print("/ \\ ")
def boat():
    print()
    print("⛅")
    print("                     |\\ ")
    print("                     | \\  ")
    print("                     | /  ")
    print("                     |/   ")
    print("  ☻        __________|___  ")
    print(" /▌\\       \\            /")
    print("_/_\\__      \\  ◎       /")
    print("       |~~~~~\\     ⚓  /~~~~~")
    print("       |      \\______/ ")
def mc_boat():
    print()
    print("⛅")
    print("          |\\ ")
    print("       ↑  | \\  ")
    print("     ☻ |  | /  ")
    print("    /▌\\|  |/      ")
    print(" ___/_\\___|____  ")
    print(" \\            /  ")
    print("  \\  ◎       /")
    print("   \\     ⚓  /")
    print("    \\______/")
def boat_danger():
    print()
    print("⛅")
    print("          |\\ ")
    print("       ↑  | \\  ")
    print("     ☻ |  | /  ")
    print("    /▌\\|  |/       / \\")
    print(" ___/_\\___|____   / ! \\")
    print(" \\            /  /_____\\")
    print("  \\  ◎       /")
    print("   \\     ⚓  /")
    print("    \\______/")
    print("Oh no! A mob is near!")
def fish_mob():
    print()
    print("⛅")
    print("          |\\  ☁      ☁")
    print("       ↑  | \\      ☁   ______    /|")
    print("     ☻ |  | /         /      \\  / |")
    print("    /▌\\|  |/         / @  ~   \\/  |")
    print(" ___/_\\___|____      \\  ~  ~  /\\  |")
    print(" \\            /       \\______/  \\ |")
    print("  \\  ◎       /                   \\|")
    print("   \\     ⚓  /  ~     ~    ~")
    print("    \\______/       ~    ~")
def fish_attack():
    print()
    print("⛅")
    print("          |\\  ☁      ☁")
    print("       ↑  | \\     ☁   ______    /|")
    print("     ☻ |  | /        /      \\  / |")
    print("    /▌\\|⊱⊱⊱⊱⊱⊱⊱⊱⊱⊱⊱/ @  ~   \\/  |")
    print(" ___/_\\___|____     \\  ~  ~  /\\  |")
    print(" \\            /      \\______/  \\ |")
    print("  \\  ◎       /                  \\|")
    print("   \\     ⚓  /  ~     ~    ~")
    print("    \\______/       ~    ~")
def attack_fish_mob_1():
    print()
    print("⛅")
    print("          |\\  ☁      ☁")
    print("          | \\      ☁   ______    /|")
    print("     ☻ ⇁⇁➙ /         /      \\  / |")
    print("    /▌/   |/         / @  ~   \\/  |")
    print(" ___/_\\___|____      \\  ~  ~  /\\  |")
    print(" \\            /       \\______/  \\ |")
    print("  \\  ◎       /                   \\|")
    print("   \\     ⚓  /  ~     ~    ~")
    print("    \\______/       ~    ~")
def attack_fish_mob_2():
    print()
    print("⛅")
    print("          |\\  ☁      ☁")
    print("          | \\      ☁  ______    /|")
    print("     ☻    | /   ⇁⇁⇁⇁➙     \\  / |")
    print("    /▌\\   |/        / @  ~   \\/  |")
    print(" ___/_\\___|____     \\  ~  ~  /\\  |")
    print(" \\            /      \\______/  \\ |")
    print("  \\  ◎       /                  \\|")
    print("   \\     ⚓  /  ~     ~    ~")
    print("    \\______/       ~    ~")
def boat_coffee_heal():
    print()
    print("⛅")
    print("          |\\ ")
    print("          | \\  ")
    print("     ☻ ☕  | /  ")
    print("    /▌/   |/   ")
    print(" ___/_\\___|____  ")
    print(" \\            /")
    print("  \\  ◎       /")
    print("   \\     ⚓  / ")
    print("    \\______/   ")
def dead_fish_mob():
    print()
    print("⛅            V I C T O R Y ! ")
    print("          |\\  ☁      ☁")
    print("       ↑  | \\      ☁  ______     /|")
    print("     ☻ |  | /         /      \\  / |")
    print("    /▌\\|  |/         / X  ~   \\/  |")
    print(" ___/_\\___|____      \\  ~  ~  /\\  |")
    print(" \\            /       \\______/  \\ |")
    print("  \\  ◎       /                   \\|")
    print("   \\     ⚓  /  ~     ~    ~")
    print("    \\______/       ~    ~")
def dead_man_fish():
    print()
    print("       D E F E A T . . .")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("_ ♈        ______    /|")
    print("  ▌\\       /      \\  / |")
    print(" / \\      / @  ~   \\/  |")
    print("          ⚫>  ~  ~ /\\  |")
    print("           \\______/  \\ |")
    print("                      \\|")
def travelling_cart_night_1():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("_______________")
    print("|             |")
    print("|             |")
    print("|             |")
    print("|_____________|")
    print("|             |")
    print("|   S H O P   |")
    print("|_____________|")
    print()
    print(" ☻          ⚘")
    print("/▌\\        ⚘ ⚘") 
    print("/ \\ ")
def travelling_cart_night_2():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("_______________")
    print("|             |")
    print("|             |")
    print("|             |")
    print("|_____________|")
    print("|             |")
    print("|   S H O P   |")
    print("|_____________|")
    print()
    print(" ☻ -?       ⚘")
    print("/▌\\        ⚘ ⚘") 
    print("/ \\ ")
def mushu_alone():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆              ⋆")
    print("      ⋆")
    print("    ")
    print("              (\\ ♛ /)") 
    print("              (￣个￣)")
    print("             (       )")
def mc_and_mushu():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆              ⋆")
    print("      ⋆")
    print("    ")
    print(" ☻           (\\ ♛ /)") 
    print("/▌\\          (￣个￣)")
    print("/ \\          (      )")
def mushu_drinking():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆              ⋆")
    print("      ⋆")
    print("    ")
    print(" ☻           (\\ ♛ /)") 
    print("/▌\\          (￣个￣)")
    print("/ \\        Ữ<(      )")
def mushu_transformation_1():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆              ⋆")
    print("      ⋆")
    print("             (\\      /)")
    print(" ☻           ( \\ ♛ / )") 
    print("/▌\\          ( ￣个￣ )")
    print("/ \\         (         )")
def mushu_transformation_2():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆              ⋆")
    print("      ⋆     (\\       /)")
    print("            ( \\     / )")
    print("            (  \\♛ /   )") 
    print(" ☻         (  ￣个￣    )")
    print("/▌\\       (  <     <    )")
    print("/ \\      (               )")
def mushu_transformation_3():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆              ⋆")
    print("      ⋆     (\\       /)")
    print("            ( \\     / )")
    print("            (  \\♛ /   )") 
    print(" ☻         (  ￣个￣    )")
    print("/▌\\       (  <     <    )")
    print("/ \\      (               )")
def mushu_transformation_4():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆          (\\ ⋆       /)")
    print("      ⋆     ( \\       / )")
    print("            (  \\     /  )")
    print("            (   \\♛ /   )") 
    print(" ☻         (    ⊙个⊙    )")
    print("/▌\\       (  <       <   )")
    print("/ \\      (                )")
def mushu_transformation_5():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆          (\\ ⋆       /)")
    print("      ⋆     ( \\       / )")
    print("            (  \\     /  )")
    print("   ↑        (   \\♛ /   )") 
    print(" ☻ |       (    ⊙个⊙    )")
    print("/▌\\|      (  <       <   )")
    print("/ \\      (                )")
def mushu_attack():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆          (\\ ⋆       /)")
    print("      ⋆     ( \\       / )")
    print("            (  \\     /  )")
    print("↑           (   \\♛ /   )") 
    print("| ☻(⊙个⊙)))))))))))))   )")
    print("|/▌\\       (  <       <   )")
    print(" / \\      (                )")
def attack_mushu():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆       (\\  ⋆      /)")
    print("      ⋆  ( \\       / )")
    print("         (  \\     /  )")
    print("         (   \\♛ /   )") 
    print(" ☻__--->(    ⊙个⊙    )")
    print("/▌     (  <       <   )")
    print("/ \\   (                )")
def final_victory_1():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆          (\\ ⋆       /)")
    print("      ⋆     ( \\       / )")
    print("            (  \\     /  )")
    print("   ↑        (   \\♛ /   )") 
    print(" ☻ |       (    ⊙个⊙    )")
    print("/▌\\|       ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡ ")
    print("/ \\        ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡")
def final_victory_2():
    print("⛅")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print(" ⋆          (\\ ⋆       /)")
    print("      ⋆     ( \\       / )")
    print("   ↑       ◠◡◠◡◠◡◠◡♛◠◡◠◡◠◡") 
    print(" ☻ |       ◠◡◠◡◠◡⊙个⊙◠◡◠◡◠◡")
    print("/▌\\|       ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡")
    print("/ \\        ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡")
def final_victory_3():
    print("☀")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("              ")
    print("              ")
    print("            ")
    print("↑         ") 
    print("| ☻__♛ ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠     ")
    print("|/▌     ◠◡◠◡◠◡◠◡◠◡⊙个⊙◡◠◡◠◡◠◡◠◡◠◡    ")
    print(" / \\    ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠ ")
def final_victory_4():
    print("☀")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("              ")
    print("              ")
    print("            ")
    print(" ♛↑       ") 
    print(" ☻ |  ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠     ")
    print("/▌\\|  ◠◡◠◡◠◡◠◡◠◡⊙个⊙◡◠◡◠◡◠◡◠◡◠◡    ")
    print("/ \\   ◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠ ")
def victory_statement():
    print("      V I C T O R Y ! ! !")
def final_defeat_1():
    print("☾")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("⋆     (\\ ⋆       /)")
    print("   ⋆  ( \\       / )")
    print("      (  \\     /  )")
    print("      (   \\♛ /   )") 
    print("     (    ⊙个⊙    )")
    print("    __▂⚫<      <   )")
    print("    (                )")
def final_defeat_2():
    print("⛅")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("⋆     (\\ ⋆       /)")
    print("   ⋆  ( \\       / )")
    print("      (  \\     /  )")
    print("      (   \\♛ /   )") 
    print("     (    ⊙个⊙    )")
    print("    (  < ______<   )")
    print("   (     \\__▂⚫/    )")
    print("  (       \\__/       )")
def final_defeat_3():
    print("☀")
    print("  ⋆        ⋆⋆ ")
    print("       ⋆")
    print("     ⋆  ⋆")
    print("⋆     (\\ ⋆       /)")
    print("   ⋆  ( \\       / )")
    print("      (  \\     /  )")
    print("      (   \\♛ /   )") 
    print("     (    ⊙个⊙    )")
    print("    (  < ______<    )")
    print("   (                 )")
def defeat_statement():
    print("     D E F E A T . . . ")
def end_screen():
    print(" ♛↑")
    print(" ☻ |")
    print("/▌\\|")
    print("/ \\")
